import "@/styles/globals.css";

import { PlaygroundLink } from "@/components/util/PlaygroundLink";
import { TailwindIndicator } from "@/components/util/TailwindIndicator";
import { cn } from "@/lib/utils";
import { TRPCReactProvider } from "@/trpc/TrpcProvider";
import type { Metadata } from "next";
import { Manrope, Rubik } from "next/font/google";
import type { PropsWithChildren } from "react";
import Providers from "./Providers";
import { AppSidebar } from "@/components/layout/app-sidebar";

const fontCaption = Manrope({ subsets: ["latin"], variable: "--font-caption" });
const fontSans = Rubik({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Temple Team | Parkour Freerun Gymnastique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: PropsWithChildren<{
  modal?: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="group/html h-screen w-screen ltr" data-scroll="0" suppressHydrationWarning>
      <body
        className={cn(
          "h-full font-sans antialiased ",
          fontSans.variable,
          fontCaption.variable,
        )}
      >
        <TRPCReactProvider>
          <Providers>
            <div
              id="main-content"
              className="flex h-full flex-col w-full min-h-svh"
            >
             {children}
            </div>
            <AppSidebar />
            <PlaygroundLink />
            <TailwindIndicator />
            {modal}
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
