import type { Metadata } from "next";
import { Manrope, Rubik } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import { cookies } from "next/headers";
import { TRPCReactProvider } from "@/components/trpc/TrpcProvider";
import { PropsWithChildren } from "react";
import { cn } from "@/lib/utils";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { TailwindIndicator } from "@/components/util/TailwindIndicator";

const fontCaption = Manrope({ subsets: ["latin"], variable: "--font-caption" });
const fontSans = Rubik({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Temple Team | Parkour Freerun Gymnastique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: PropsWithChildren<{
  modal?: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className="group/html h-full"
      data-scroll="0"
      suppressHydrationWarning
    >
      <body className={cn("w-full font-sans antialiased", fontSans.variable)}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Providers>
            <div className="relative flex flex-col overflow-x-hidden">
              <Header />
              <div className="relative grid top-[60px] flex-1 auto-rows-auto gap-6 pb-10 pt-5 md:top-[70px] lg:top-[80px]" aria-hidden="true">
                {children}
              </div>
              <Footer />
            </div>
            <TailwindIndicator />
            {modal}
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
