import * as z from "zod";
import { CompleteReferences, RelatedReferencesModel } from "./index";

export const ReferenceCategoryModel = z.object({
  /**
   * The unique identifier for the category of References
   * @default {Generated by database}
   */
  id: z.number().int(),
  /**
   * Name of the References
   */
  name: z.string(),
});

export interface CompleteReferenceCategory
  extends z.infer<typeof ReferenceCategoryModel> {
  References: CompleteReferences[];
}

/**
 * RelatedReferenceCategoryModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedReferenceCategoryModel: z.ZodSchema<CompleteReferenceCategory> =
  z.lazy(() =>
    ReferenceCategoryModel.extend({
      References: RelatedReferencesModel.array(),
    }),
  );
