import * as z from "zod";
import {
  CompleteAccount,
  CompleteSession,
  RelatedAccountModel,
  RelatedSessionModel,
} from "./index";

export const UserModel = z.object({
  /**
   * The unique identifier for the User
   * @default {Generated by database}
   */
  id: z.string(),
  /**
   * name of the user (username)
   */
  name: z.string().nullish(),
  /**
   * unique for each user
   * logical index
   */
  email: z.string().nullish(),
  /**
   * Date wen user email has been verified
   */
  emailVerified: z.date().nullish(),
  /**
   * name of user image
   */
  image: z.string().nullish(),
  password: z.string().max(255).nullish(),
});

export interface CompleteUser extends z.infer<typeof UserModel> {
  accounts: CompleteAccount[];
  sessions: CompleteSession[];
}

/**
 * RelatedUserModel contains all relations on your model in addition to the scalars
 *
 * NOTE: Lazy required in case of potential circular dependencies within schema
 */
export const RelatedUserModel: z.ZodSchema<CompleteUser> = z.lazy(() =>
  UserModel.extend({
    accounts: RelatedAccountModel.array(),
    sessions: RelatedSessionModel.array(),
  }),
);
