import * as z from "zod";

export const YoutubeVideosModel = z.object({
  /**
   * The unique identifier of the video
   * @default {Generated by Youtube API}
   */
  id: z.string(),
  /**
   * Title of the video
   */
  title: z.string(),
  /**
   * Filename of the thumbnail
   */
  thumbnail: z.string(),
  /**
   * Category of the video
   */
  category: z.string(),
  /**
   * Date when the video has been published
   */
  publishedAt: z.date(),
});
